# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="EXIFTOOL"
DIST_VERSION="12.60"


inherit perl-module

DESCRIPTION="Read and write meta information"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~arm64 ~amd64"
IUSE=""

DEPEND="dev-perl/Archive-Zip
	dev-lang/perl"
